### ISSUE TITLE
Add remaining test cases for `apply_nan_mode`

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#1108]
Function to add test cases for - https://github.com/kaizen-ai/kaizenflow/blob/423470c58122af11b12a1b9c3ea889abcad52342/helpers/hdataframe.py#L163

Few tests are already added over here - https://github.com/kaizen-ai/kaizenflow/blob/423470c58122af11b12a1b9c3ea889abcad52342/helpers/test/test_dataframe.py#L120

Analyze what tests are remaining and add more tests.

See unit test [doc](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) to follow the code style
Also highly recommend to read this [doc](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md#save-reviewer-time) before submitting the PR

FYI @gpsaggese @sonaalKant @DanilYachmenev

**Comment by mihir1906** [comment]
test_dataframe.py::Test_apply_nan_mode::test1 (0.02 s) PASSED                                                                                                                                       [ 10%]
test_dataframe.py::Test_apply_nan_mode::test2 (0.01 s) PASSED                                                                                                                                       [ 20%]
test_dataframe.py::Test_apply_nan_mode::test3 (0.01 s) PASSED                                                                                                                                       [ 30%]
test_dataframe.py::Test_apply_nan_mode::test4 (0.01 s) PASSED                                                                                                                                       [ 40%]
test_dataframe.py::Test_apply_nan_mode::test5 (0.01 s) PASSED                                                                                                                                       [ 50%]
test_dataframe.py::Test_apply_nan_mode::test10 (0.20 s) PASSED                                                                                                                                      [ 60%]
test_dataframe.py::Test_apply_nan_mode::test6 (0.00 s) PASSED                                                                                                                                       [ 70%]
test_dataframe.py::Test_apply_nan_mode::test7 (0.00 s) PASSED                                                                                                                                       [ 80%]
test_dataframe.py::Test_apply_nan_mode::test8 (0.00 s) PASSED                                                                                                                                       [ 90%]
test_dataframe.py::Test_apply_nan_mode::test9 (0.00 s) PASSED                                                                                                                                       [100%]


(amp.client_venv) mihir@mihir-VMware-Virtual-Platform:~/src/kaizenflow1$ invoke docker_bash
docker pull 623860924167.dkr.ecr.eu-north-1.amazonaws.com/cmamp:dev
Error response from daemon: Head "https://623860924167.dkr.ecr.eu-north-1.amazonaws.com/v2/cmamp/manifests/dev": no basic auth credentials

@samarth9008 @sonaalKant I am getting this error while starting the docker container. Do I need any credentials for accessing the docker container?

**Comment by samarth9008** [comment]
Let take a look later.

**Comment by samarth9008** [comment]
Should work now.

**Comment by mihir1906** [comment]
> Should work now.

Still getting the same error. Any suggestions on how can I debug this?

**Comment by samarth9008** [comment]
Did you pull the latest master?

**Comment by mihir1906** [comment]
It's working now! Thank you.
